# Generated by Django 2.0.2 on 2018-02-13 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labday_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='path',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='place',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='speaker',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='timetable',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='latitude',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='latitude',
            field=models.TextField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='place',
            name='longitude',
            field=models.TextField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
