# Generated by Django 2.0.2 on 2018-03-19 19:38

from django.db import migrations
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('labday_api', '0005_auto_20180318_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='position',
            field=geoposition.fields.GeopositionField(blank=True, max_length=42),
        ),
    ]
