# Generated by Django 2.0.2 on 2018-03-19 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labday_api', '0006_place_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='latitude',
            field=models.TextField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='place',
            name='longitude',
            field=models.TextField(blank=True, max_length=20),
        ),
    ]
