# Generated by Django 2.0.2 on 2018-03-19 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labday_api', '0007_auto_20180319_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='latitude',
            field=models.TextField(blank=True, editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='place',
            name='longitude',
            field=models.TextField(blank=True, editable=False, max_length=20),
        ),
    ]
