# Generated by Django 2.0.2 on 2018-03-20 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labday_api', '0008_auto_20180319_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='event_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='labday_api.Event'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='path_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='labday_api.Path'),
        ),
    ]
