# Generated by Django 2.0.2 on 2018-03-21 18:54

from django.db import migrations
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('labday_api', '0009_auto_20180320_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='position',
            field=geoposition.fields.GeopositionField(blank=True, max_length=42),
        ),
    ]
