# Generated by Django 2.0.2 on 2018-03-21 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labday_api', '0010_event_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='latitude',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='longitude',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='place',
            name='latitude',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='place',
            name='longitude',
            field=models.TextField(blank=True, editable=False),
        ),
    ]
